"""
State management for the Deep Research Agent.
"""

from typing import List, TypedDict, Optional, Annotated, Any
import operator
from dataclasses import dataclass

@dataclass
class ResearchNote:
    """A single piece of information extracted from a source."""
    title: str
    url: str
    content: str
    relevance: str

class AgentState(TypedDict):
    """The internal state of the Deep Research Agent."""
    # The original user request
    query: str
    
    # The systematic research outline generated at the start
    outline: List[str]
    
    # Current section we are working on
    current_section_index: int

    # List of sub-queries generated by the planner
    sub_queries: List[str]
    
    # Accumulated research notes
    # Annotated with operator.add to allow merging results from parallel nodes
    notes: Annotated[List[ResearchNote], operator.add]
    
    # Drafted sections of the report
    report_sections: Annotated[List[str], operator.add]
    
    # List of URLs already visited to avoid duplicates
    visited_urls: Annotated[List[str], operator.add]
    
    # Internal counter for the loops
    loop_count: int
    
    # The final research report
    report: Optional[str]
    
    # Reflection result: whether more info is needed
    needs_more_info: bool
    
    # Reasoning for the next steps
    next_steps_reasoning: str
    
    # Reference to the graph for cancellation checks
    graph: Any
